language: "python"
dist: "precise"
python:
    - "3.6"
cache: "pip"
install:
    - "pip install .[tests]"
script:
    - "DATA_DIR=$PWD/data pytest -v"
# deploy:
#     provider: "script"
#     script: "curl -X POST http://pyworking.cz:9000/deploy/pyworking.cz"
#     on:
#         branch: "master"
#         python: "3.6"
#         repo: "pyvec/pyworking.cz"
